// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpnmseipngvepvdgbsrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwbm1zZWlwbmd2ZXB2ZGdic3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODMxNjMsImV4cCI6MjA2MTE1OTE2M30.ifiHiBuxEVtQl0grTh_bG3oUuZ-Oyb2qSX1NCTcjIWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);